base/urls.py
from django.urls import path
from base.views.dashboard_view import Dashboard
from base.views.auth_view import UserLoginView, LogoutView
from base.views.category_view import    CategoryDeleteView
from base.views.inventory_view import CreateInventoryView, InventoryListView, InventoryDetailView, \
    InventoryUpdateView, InventoryDeleteView
from base.views.tag_view import CreateListTagView, TagDeleteView
from base.views.product_view import  ProductListView, eventSellingproduct,lowProduct,expireProduct, lowSellingproduct, topSellingproduct
from base.views.logout import logout_view
from base.views.pos_view import POSView, cart_add, cart_updated, cart_remove
from base.views.order_views import bulling_information_view, OrderItemView, search_orders
from base.views.group import startGroup,manageGroup,updateGroup,deleteGroup
from base.views.user import startUser, manageuser, updateuser, deleteuser, user_profile
from base.views.orderView import *
from base.views.product_view import (
    create_product, update_product, delete_product, search_products
)
from base.views.category_view import (
    create_category, update_category, categories
)
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', Dashboard, name='dashboard'),
    # path('create-category/', CategoryCreateView.as_view(), name='create_category'),
    path('create-category/', create_category, name='create_category'),
    path('update-category/<int:cat_id>/', update_category, name='update_category'),
    path('category/', categories, name='category_list'),
    # path('category/<pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('create-inventory/', CreateInventoryView.as_view(), name='inventory_create'),
    path('inventory/', InventoryListView.as_view(), name='inventory_list'),
    path('inventory/<pk>/', InventoryDetailView.as_view(), name='inventory_detail'),
    path('inventory-update/<pk>/', InventoryUpdateView.as_view(), name='inventory_update'),
    path('inventory-delete/<pk>/', InventoryDeleteView.as_view(), name='inventory_delete'),
    path('tag/', CreateListTagView.as_view(), name='create_list_tag'),
    path('tag/<pk>/', TagDeleteView.as_view(), name='tag_delete'),
    # path('create-product/', CreateProductView.as_view(), name='product_create'),
    path('product-list/', ProductListView.as_view(), name='product_list'),
    path('create-product/', create_product, name='product_create'),
    path('update-product/<int:product_id>', update_product, name='product_update'),
    path('delete-product/<int:product_id>', delete_product, name='delete_update'),
    path('search-products/', search_products, name='search_products'),
    path('cart/id/', cart_add, name='cart_add'),
    path('cart-update/<int:id>/', cart_updated, name='cart_updated'),
    path('cart-remove/<int:id>/', cart_remove, name='cart_remove'),
    path('pos/', POSView.as_view(), name='pos_view'),
    path('bulling-infromation/', bulling_information_view, name='bulling_information'),
    path('order-infromation/', OrderItemView.as_view(), name='order_information'),
    path('add_group/', startGroup, name='add_group'),
    path('manageGroup/', manageGroup, name='manageGroup'),
    path('group-update/<int:group_id>/', updateGroup, name='group_update'),
    path('group-delete/<pk>', deleteGroup, name='group_delete'),
    path('add_user/', startUser, name='add_user'),
    path('manageuser/', manageuser, name='manageuser'),
    path('user-profile/<int:profile_id>/', user_profile, name='user_profile'),


    path('user-update/<int:user_id>/', updateuser, name='user_update'),
    path('user-delete/<pk>', deleteuser, name='user_delete'),
    path('logout', logout_view, name='logout'),
    path('low-product', lowProduct, name='low-product'),
    path('expireProduct', expireProduct, name='expire-Product'),
    path('topSellingProduct', topSellingproduct, name='top-selling-Product'),
    path('lowSellingproduct', lowSellingproduct, name='low-selling-Product'),
    path('eventSellingproduct', eventSellingproduct, name='event-selling-Product'),
    # path('add_order', add_order, name='Add-order'),
    path('invoice', invoice, name='Add-order'),
    path('viewOrder', viewOrder, name='view-order'),
    path('order-update/<int:pk>/', updateOrder, name='order_update'),
    path('order-delete/<pk>/', deleteOrder, name='order_delete'),
    path('search-orders/', search_orders, name='search_orders'),
    path('load-price', load_price, name='load-price'),

    path('create_order/', create_order, name='create_order'),
    path('get_product/', get_product, name='get_product'),
    path('ajax_create_order/', ajax_order_create, name='ajax_create_order'),
]

inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    # path('config/', include('product.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models/EventModel.py
from datetime import datetime
from django.db import models

from base.models.base import BaseEntity
from base.models.product import Product


# order by user

base/models/Invoice.py
from django.db import models
from datetime import datetime
from django.db.models.deletion import CASCADE

from django.db.models.fields import AutoField
from base.models.base import BaseEntity
from base.models.category import Category
from base.models import Tag,Product,Category
from django.contrib.auth.models import User

class Event(models.Model):
    event_name = models.CharField(default="",max_length=122)
    def __str__(self):
        return self.event_name

class Invoice(BaseEntity):
    Product_id = models.ForeignKey(Product,max_length=122,on_delete=models.CASCADE,default=1)
    Event_Name = models.ForeignKey(Event,on_delete=CASCADE)
    sold_Quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0,null=True)
    total_price = models.FloatField(default=0, null = True)
    date_time = models.DateField(default=datetime.today)
    
    def __str__(self):
        return self.Product_id.product_name+" "+str((self.date_time))

base/models/base.py
from django.db import models


class BaseEntity(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

base/models/cart.py
from django.db import models
from base.models.base import BaseEntity
from base.models.product import Product


class Cart(BaseEntity):
    products = models.ManyToManyField(Product, null=True)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.total

base/models/category.py
from django.db import models
from base.models.base import BaseEntity


class Category(BaseEntity):
   
   category_name = models.CharField(default=" ",max_length=122)
   product_id = models.IntegerField(default=0)
   name  = models.CharField(max_length=122,default="")
   parent = models.CharField(max_length=122,default="")
   status = models.IntegerField(default=0)
    
   def __str__(self):
        return self.category_name

   

base/models/group.py
from django.db import models

base/models/product.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import AutoField, FloatField
from base.models.base import BaseEntity
from base.models.category import Category
from datetime import datetime

# order by user
class Product(BaseEntity):
  
    product_name = models.CharField(max_length=180,null=True)
    Quantity = models.CharField(max_length=122,default=0)
    Price = FloatField(default=0)
    expiry_date = models.DateField(default=datetime.today)
    manufactor_date = models.DateField(default=datetime.today)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product',default=0)
    datetime = models.DateField(default=datetime.today)
    description = models.TextField(max_length=500)
    stock = models.IntegerField(default=0)
    count_sold = models.IntegerField(default=0)
    product_uuid = models.IntegerField(blank=True, null=True)

    def __str__(self):
         return self.product_name

base/models/tag.py
from django.db import models
from base.models.base import BaseEntity


class Tag(BaseEntity):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name

base/forms/EventForm.py
from django import forms
from django.forms import TextInput, Select, FileInput, CheckboxInput
from base.models.Invoice import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        widgets = {
            'event_name': Select(attrs={'class': 'form-control'}),
        }

base/forms/UserForm.py
from django import forms
from django.forms import TextInput, Select, FileInput, CheckboxInput, EmailInput, NumberInput, PasswordInput, IntegerField
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    phn_number = forms.IntegerField()
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'phn_number',
                  'last_name']


class UpdateUserForm(forms.ModelForm):
    phn_number = forms.IntegerField()
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'phn_number', 
                  'last_name']

        widgets = {
            'username': TextInput(attrs={'class': 'form-control', 'id': 'username', 'placeholder': 'Your Username'}),
            'email': EmailInput(attrs={'class': 'form-control', 'id': 'email', 'placeholder': 'Enter email address'}),
            'phn_number': IntegerField(),
            'first_name': TextInput(attrs={'class': 'form-control', 'id': 'first_name', 'placeholder': 'Your First Name'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'id': 'last_name', 'placeholder': 'Your Last Name'}),
            'password1': PasswordInput(attrs={'class': 'form-control', 'id': 'password1', 'placeholder': 'Your password1'}),
            'password2': PasswordInput(attrs={'class': 'form-control', 'id': 'password2', 'placeholder': 'Your password2'}),
        }
        

base/forms/category_form.py
from django import forms
from django.forms import TextInput, Select, FileInput, CheckboxInput
from base.models.category import Category


class CreateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name',  'status', 'parent']

        # widgets = {
        #     'name': TextInput(attrs={'class': 'form-control', 'id': 'name'}),
        #     'parent': Select(attrs={'class': 'form-control'}),
        #     'category_image': FileInput(attrs={'class': 'form-control', 'id': 'imageUpload'}),
        #     'is_active': CheckboxInput(attrs={'class': 'checkbox', 'id': 'activity'})
        # }


class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name',  'status', 'parent']

base/forms/group_form.py
from django.contrib.auth.models import Group, Permission
from django import forms


class UpdateGroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = '__all__'

base/forms/inventory_form.py
from django import forms
from django.forms import TextInput, Select, FileInput, NumberInput, Textarea, SelectMultiple

from base.models.inventory import Inventory


class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter Inventory Name'}),
            'category_name': Select(attrs={'class': 'form-control', 'id': 'category_name'}),
            'tags': SelectMultiple(attrs={'class': 'form-control select2', 'id': 'tags', 'multiple': 'multiple'}),
            'short_description': TextInput(
                attrs={'class': 'form-control', 'id': 'short_description',
                       'placeholder': 'Enter inventory shot description'}),
            'full_description': Textarea(attrs={'class': 'form-control', 'id': 'full_description',
                                                'placeholder': 'Enter inventory full description'}),
            'current_stock': NumberInput(attrs={'class': 'form-control', 'id': 'current_stock'}),
            'purchase_price': NumberInput(attrs={'class': 'form-control', 'id': 'purchase_price'}),
            'sales_price': NumberInput(attrs={'class': 'form-control', 'id': 'sales_price'}),
            'promotional_price': NumberInput(attrs={'class': 'form-control', 'id': 'promotional_price'}),
            'picture': FileInput(attrs={'class': 'form-control', 'id': 'picture'}),
        }

base/forms/invoice_form.py
from base.models import product
from base.models.product import Product
from base.models.order import OrderItem
from django import forms
from django.db.models.fields import DateField
from django.forms import TextInput, Select, FileInput, NumberInput, Textarea, SelectMultiple
from django.forms.widgets import DateInput

from base.models.Invoice import Invoice


class InvoiceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['price'].queryset = Product.objects.only('Price').get(product_name="HP")

    class Meta:
        model = Invoice
        fields = '__all__'
        widgets = {
            'Product_id': Select(attrs={'class': 'form-control', 'id': 'product_name'}),
            'Event_Name': Select(attrs={'class': 'form-control', }),
            'sold_Quantity': NumberInput(attrs={'class': 'form-control', 'id': 'qty'}),
            'price': TextInput(attrs={'class': 'form-control', 'id': 'price'}),
            'total_price': TextInput(attrs={'class': 'form-control', 'id': 'total_price'}),
            'date_time': DateInput(attrs={'class': 'form-control',}),
        }


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['orderItem'].widget.attrs['hidden'] = True

base/forms/login_form.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Username', 'required': True, 'autofocus': True}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Password', 'required': True}))
    remember_me = forms.BooleanField(required=False)

base/forms/order_form.py
from django.forms import ModelForm
from django.forms import TextInput, NumberInput, EmailInput

from base.models.order import Order, OrderItem


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

        widgets = {
            'full_name': TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter Full Name'}),
            'email': EmailInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter email address'}),
            'phn_number': NumberInput(attrs={'class': 'form-control', 'id': 'phn_number'}),
            'address': TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter address'})
        }


class UpdateOrderForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

        # widgets = {
        #     'full_name': TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter Full Name'}),
        #     'email': EmailInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter email address'}),
        #     'phn_number': NumberInput(attrs={'class': 'form-control', 'id': 'phn_number'}),
        #     'address': TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Enter address'})
        # }

base/forms/product_form.py
from django import forms
from django.forms import TextInput, Select, FileInput, NumberInput, Textarea

from base.models.product import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_uuid', 'product_name',  'Price', 'expiry_date',
                  'manufactor_date', 'category_id', 'description', 'stock', 'count_sold']
        # widgets = {
        #     'product_name': TextInput(attrs={'class': 'form-control', 'id': 'title', 'placeholder': 'Enter Product Name'}),
        #     'product_category': Select(attrs={'class': 'form-control', 'id': 'product_category'}),
        #     'price': NumberInput(attrs={'class': 'form-control', 'id': 'price'}),
        #     'description': Textarea(attrs={'class': 'form-control', 'id': 'description', 'placeholder': "Your Product's history here"}),
        #     'product_image': FileInput(attrs={'class': 'form-control', 'id': 'product_image'}),
        # }
class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_uuid', 'product_name', 'Quantity', 'Price', 'expiry_date',
                  'manufactor_date', 'category_id', 'description', 'stock', 'count_sold']

base/templates/product/Event.html
{% extends 'base.html' %}

{% block title %} Add new Product {% endblock %}

{% block content %}

    <section class="content-header">
        <h1> Dashboard <small>Add new Category</small></h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Category</li>
        </ol>
    </section>

    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <div class="row">
                            <div class="col-lg-6">
                                <h3 class="box-title">Select Any Event</h3>
                            </div>
                            <div class="col-lg-6 text-right">
                                <a title="Category list" data-toggle="tooltip" data-placement="left"
                                   class="btn btn-info btn-sm" href="{% url 'category_list' %}">
                                    <i class="fa fa-list"></i>
                                </a>
                            </div>
                        </div>
                        {% include 'common/message.html' %}
                    </div>
                    <div class="box-body">
                        <form method="POST" enctype="multipart/form-data" action="eventSellingproduct">
                            {%csrf_token%}
                           
                            <select name="event" id="" class="form-control">
                                {%for even in event%}
                                <option value="{{even.baseentity_ptr}}">
                                    {{even.event_name}}
                                </option>
                                {%endfor%}
                            </select>
                            <button class="btn btn-success" type="submit">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

base/templates/product/delete_product.html
{% extends 'base.html' %}

{% block title %} {{ object }} confirm delete {% endblock %}

{% block content %}
    <div class="content">
        <div class="row text-center">
            <div class="col-lg-6 col-lg-offset-3 text-center mt-5">
                <div class="box">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="card pt-3">
                            <div class="card-header">
                                <h5 class="card-title">Are you sure will you want to delete "{{ object }}"?</h5>
                            </div>
                            <div class="card-body">
                                <button class="btn btn-danger btn-sm" type="submit">Yes</button>
                                <a href="{% url 'product_list' %}" class="btn btn-warning btn-sm  text-light">No</a>
                            </div>
                        </div>
                    </form>
                    <br/>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

base/templates/product/product_list_component.html
{% if product %}
<div class="box-body">
   
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Product ID</th>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Price</th>
                <th>Manufacturing Date</th>
                <th>Expire Date</th>
                <th>Added on date</th>
                <th>Description</th>
                <th>Stock</th>
                
                {% if perms.base.add_product or perms.base.change_product %}
                <th class="text-center">Action</th>
                {% endif %}
            </tr>
            {% for obj in product %}
                <tr>
                    <td>{{ obj.product_uuid }}</td>
                    <td>{{ obj.product_name }}</td>
                    <td>{{ obj.category_id.category_name}}</td>
                    <td>{{ obj.Price }}</td>
                    <td>{{ obj.manufactor_date}}</td>
                    <td>{{ obj.expiry_date}}</td>
                    <td>{{ obj.datetime}}</td>
                    <td>{{ obj.description}}</td>
                    <td>{{ obj.stock }}</td>                  
                    <!-- <td>
                        {% if not obj.product_image %}
                            <div class="image_not_found"><i class="fa fa-desktop"></i></div>
                        {% else %}
                            <img width="40px" height="15" src="/media/{{ obj.product_image }}"
                                 alt="category image">
                        {% endif %}
                    </td> -->
                        
                    <td class="text-center">
                        {% if perms.base.change_product %}
                        <a class="btn btn-info btn-sm" href="{% url 'product_update' obj.pk %}"><i class="fa fa-pencil"></i></a>
                        {% endif %}
                        {% if perms.base.delete_product %}
                            <a class="btn btn-danger btn-sm" href="{% url 'delete_update' obj.pk %}"><i class="fa fa-trash"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
</div>
{% endif %}
</div>
<!-- Low Stock          -->
{% if lowproduct %}
<div class="box-body">
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Price</th>
                <th>Expire Date</th>
                <th>Stock</th>
                {%if perms.base.add_product or perms.base.change_product%}
                <th class="text-center">Action</th>
                {%endif%}
            </tr>
            {% for obj in lowproduct %}
            {%if obj.stock < 5 %}
                <tr>
                    <td>{{ obj.product_name }}</td>
                    <td>{{obj.category_id.category_name}}</td>
                    
                    <td>{{ obj.Price }}</td>
                    <td>{{obj.expiry_date}}</td>
                    <td>{{ obj.stock }}</td>                  
                    <td>
                        {% if not obj.product_image %}
                            <div class="image_not_found"><i class="fa fa-desktop"></i></div>
                        {% else %}
                            <img width="40px" height="15" src="/media/{{ obj.product_image }}"
                                 alt="category image">
                        {% endif %}
                    </td>
                        
                    <td class="text-center">
                        {% if perms.base.change_product %}
                        <a class="btn btn-info btn-sm" href="#"><i
                                class="fa fa-pencil"></i></a>{%endif%}
                        {% if perms.base.delete_product %}
                        <a class="btn btn-danger btn-sm" href="#"><i
                                class="fa fa-trash"></i></a>{%endif%}
                    </td>
                </tr>
                {%endif%}
            {% endfor %}
        </tbody>
        </table>


        <!-- Low Stock          -->
    
</div>
{% endif %}

<div class="box-body">
    {% if expireProducts %}
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Price</th>
                <th>Expire Date</th>
                <th>Stock</th>
                 {%if perms.base.add_product or perms.base.change_product%}
                <th class="text-center">Action</th>
                {%endif%}
            </tr>
            {% for obj in expireProducts %}
            
                <tr>
                    <td>{{ obj.product_name }}</td>
                    <td>{{obj.category_id.category_name}}</td>
                    
                    <td>{{ obj.Price }}</td>
                    <td>{{obj.expiry_date}}</td>
                    <td>{{ obj.stock }}</td>                           
                    <td>
                        {% if not obj.product_image %}
                            <div class="image_not_found"><i class="fa fa-desktop"></i></div>
                        {% else %}
                            <img width="40px" height="15" src="/media/{{ obj.product_image }}"
                                 alt="category image">
                        {% endif %}
                    </td>
                        
                    <td class="text-center">
                        {% if perms.base.change_product %}
                        <a class="btn btn-info btn-sm" href="#"><i
                                class="fa fa-pencil"></i></a>{%endif%}
                        {% if perms.base.delete_product %}
                        <a class="btn btn-danger btn-sm" href="#"><i
                                class="fa fa-trash"></i></a>{%endif%}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>


        <!-- Expire Prducts          -->

</div>
{% endif %}




<div class="box-body">
    {% if topSellingproduct %}
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Price</th>
                <th>Count Sold</th>
                <th>Expire Date</th>
                <th>Stock</th>
            </tr>
            {% for obj in topSellingproduct %}
            
                <tr> <td>{{ obj.product_name }}</td>
                    <td>{{obj.category_id.category_name}}</td>
                    
                    <td>{{ obj.Price }}</td>
                    <td>{{obj.count_sold}}</td>
                    <td>{{obj.expiry_date}}</td>
                    <td>{{ obj.stock }}</td>                        
                    
                </tr>
            {% endfor %}
        </tbody>
        </table>


        <!-- Expire Prducts          -->

</div>
{% endif %}
</div>





<div class="box-body">
    {% if lowSellingproduct %}
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Price</th>
                <th>Count Sold</th>
                <th>Expire Date</th>
                <th>Stock</th>
            </tr>
            {% for obj in lowSellingproduct %}
            
                <tr>
                    <td>{{ obj.product_name }}</td>
                    <td>{{obj.category_id.category_name}}</td>
                    
                    <td>{{ obj.Price }}</td>
                    <td>{{obj.count_sold}}</td>
                    <td>{{obj.expiry_date}}</td>
                    <td>{{ obj.stock }}</td>               
                    
                </tr>
            {% endfor %}
        </tbody>
        </table>


        <!-- Expire Prducts          -->

</div>
{% endif %}
</div>






<div class="box-body">
    {% if eventSellingproduct %}
        <table class="table table-bordered">
            <tbody>
            <tr>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Price</th>
                <th>Expire Date</th>
                <th>Stock</th> {%if perms.base.add_product or perms.base.change_product%}
                <th class="text-center">Action</th>
                {%endif%}
            </tr>
            {% for obj in eventSellingproduct %}
            
                <tr>
                    <td>{{ obj.product_name }}</td>
                    <td>{{obj.category_id.category_name}}</td>
                    
                    <td>{{ obj.Price }}</td>
                    <td>{{obj.expiry_date}}</td>
                    <td>{{ obj.stock }}</td>               
                    <td>
                        {% if not obj.product_image %}
                            <div class="image_not_found"><i class="fa fa-desktop"></i></div>
                        {% else %}
                            <img width="40px" height="15" src="/media/{{ obj.product_image }}"
                                 alt="category image">
                        {% endif %}
                    </td>
                        
                    <td class="text-center">
                        {% if perms.base.change_product %}
                        <a class="btn btn-info btn-sm" href="#"><i
                                class="fa fa-pencil"></i></a>{%endif%}
                        {% if perms.base.delete_product %}
                        <a class="btn btn-danger btn-sm" href="#"><i
                                class="fa fa-trash"></i></a>{%endif%}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        </table>


        <!-- Expire Prducts          -->

</div>
{% endif %}
</div>